import socket
import threading
import traceback
import PyQt5.QtCore
from PyQt5.QtCore import QRect, QMetaObject, QCoreApplication, Qt, QDir, QRunnable, pyqtSlot, QThreadPool, \
    QObject, QTimer, QThread, pyqtSignal
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QLineEdit, QVBoxLayout, QWidget, QLCDNumber, QComboBox, \
    QCompleter, QGroupBox, QFormLayout, QPushButton, QPlainTextEdit, QMenuBar, QStatusBar, QListView, QListWidget, \
    QSplitter, QFileDialog, QAbstractScrollArea, QTableWidgetItem, QTableWidget, QProgressBar, QGridLayout
import requests
import sys
from random import choice
import ipaddress  # for ipv4 validation
import os
import time
import webbrowser  # for opening cell double click into browser
import csv


class ScannerThread(QObject):
    finished = PyQt5.QtCore.pyqtSignal()
    progress_signal = pyqtSignal(int)
    result_signal = pyqtSignal(str)

    def __init__(self, hosts, ports):
        QThread.__init__(self)
        self.ports_result = ""
        self.hosts = hosts
        self.result = ""
        self.ports = ports
        self.progress = 0
        self.hosts_number = len(self.hosts)

    def __del__(self):
        self.wait()

    def scan(self, host):
        self.result += "{}:".format(host)
        self.progress += 100 * (1 / self.hosts_number)
        self.progress_signal.emit(self.progress)
        for port in self.ports:
            try:
                TCPsock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                TCPsock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                TCPsock.settimeout(1)
                TCPsock.connect((host, port))

                TCPsock.close()
                self.ports_result += "{},".format(str(port))
            except Exception as e:
                self.ports_result += ""
                print("ERROR:", e)

        try:
            self.ip_address = socket.gethostbyname(host)
            self.result += "{}:".format(self.ip_address)

        except Exception as e:
            self.result += "{}:".format(host)
            print(e)
        self.result += self.ports_result
        self.result_signal.emit(self.result)
        self.result = ""
        self.ports_result = ""
        self.finished.emit()

    def run(self):
        for h in self.hosts:
            self.scan(h)

# apis is list of virustotal APIs
# get subdomains,siblings and resolutions of a domain
def get_domain_info(domain, apis):
    url = 'https://www.virustotal.com/vtapi/v2/domain/report?domain={}&apikey={}'.format(domain, choice(apis))
    domains = []
    try:
        r = requests.get(url)
        result = r.json()
        if "subdomains" in result.keys():
            for domain in result['subdomains']:
                domains.append(domain)
        if "resolutions" in result.keys():
            for domain in result['resolutions']:
                domains.append(domain['ip_address'])
        if "domain_siblings" in result.keys():
            for domain in result['domain_siblings']:
                domains.append(domain)
    except Exception as e:
        # print the line of exception
        exc_type, exc_obj, exc_tb = sys.exc_info()
        fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
        print(exc_type, fname, exc_tb.tb_lineno, e)
    return domains


# get domains related to an IP address
def get_ip_info(ip, api_key):
    url = 'https://www.virustotal.com/vtapi/v2/ip-address/report?ip={}&apikey={}'.format(ip, api_key)
    domains = []
    try:
        r = requests.get(url)
        result = r.json()
        for j in result['resolutions']:
            domains.append(j['hostname'])
        result = domains
    except Exception as e:
        # print(e)
        result = "ERROR"
    return result


# generated by PyQt Designer
class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super(QMainWindow, self).__init__()
        self.setWindowTitle("My App")

    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(844, 558)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.VirusTotal_GB = QGroupBox(self.centralwidget)
        self.VirusTotal_GB.setObjectName(u"VirusTotal_GB")
        self.VirusTotal_GB.setGeometry(QRect(595, 20, 221, 131))
        self.formLayout = QFormLayout(self.VirusTotal_GB)
        self.formLayout.setObjectName(u"formLayout")
        self.VT_Qline_L = QLabel(self.VirusTotal_GB)
        self.VT_Qline_L.setObjectName(u"VT_Qline_L")

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.VT_Qline_L)

        self.VT_Qline = QLineEdit(self.VirusTotal_GB)
        self.VT_Qline.setObjectName(u"VT_Qline")

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.VT_Qline)

        self.VT_GetIP_B = QPushButton(self.VirusTotal_GB)
        self.VT_GetIP_B.setObjectName(u"VT_GetIP_B")

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.VT_GetIP_B)

        self.VT_GetDomain_B = QPushButton(self.VirusTotal_GB)
        self.VT_GetDomain_B.setObjectName(u"VT_GetDomain_B")

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.VT_GetDomain_B)

        self.ResultListView = QListWidget(self.centralwidget)
        self.ResultListView.setObjectName(u"ResultListView")
        self.ResultListView.setGeometry(QRect(10, 190, 191, 271))
        self.loadapis = QGroupBox(self.centralwidget)
        self.loadapis.setObjectName(u"loadapis")
        self.loadapis.setGeometry(QRect(370, 20, 217, 122))
        self.gridLayout = QGridLayout(self.loadapis)
        self.gridLayout.setObjectName(u"gridLayout")
        self.label = QLabel(self.loadapis)
        self.label.setObjectName(u"label")

        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.filepath = QLineEdit(self.loadapis)
        self.filepath.setObjectName(u"filepath")

        self.gridLayout.addWidget(self.filepath, 1, 0, 1, 2)

        self.load_B = QPushButton(self.loadapis)
        self.load_B.setObjectName(u"load_B")

        self.gridLayout.addWidget(self.load_B, 2, 0, 1, 1)

        self.browse_B = QPushButton(self.loadapis)
        self.browse_B.setObjectName(u"browse_B")

        self.gridLayout.addWidget(self.browse_B, 2, 1, 1, 1)

        self.about = QGroupBox(self.centralwidget)
        self.about.setObjectName(u"about")
        self.about.setGeometry(QRect(9, 19, 351, 131))
        self.formLayout_3 = QFormLayout(self.about)
        self.formLayout_3.setObjectName(u"formLayout_3")
        self.help = QLabel(self.about)
        self.help.setObjectName(u"help")
        self.help.setWordWrap(True)

        self.formLayout_3.setWidget(0, QFormLayout.LabelRole, self.help)

        self.scan_all = QPushButton(self.centralwidget)
        self.scan_all.setObjectName(u"scan_all")
        self.scan_all.setGeometry(QRect(10, 470, 191, 25))
        self.tableWidget = QTableWidget(self.centralwidget)
        if (self.tableWidget.columnCount() < 4):
            self.tableWidget.setColumnCount(4)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(210, 160, 611, 301))
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setSortingEnabled(True)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.copy_as_csv_B = QPushButton(self.centralwidget)
        self.copy_as_csv_B.setObjectName(u"copy_as_csv_B")
        self.copy_as_csv_B.setGeometry(QRect(210, 470, 171, 25))
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(10, 160, 191, 25))
        self.splitter.setOrientation(Qt.Horizontal)
        self.Clear = QPushButton(self.splitter)
        self.Clear.setObjectName(u"Clear")
        self.splitter.addWidget(self.Clear)
        self.CopyResult_B = QPushButton(self.splitter)
        self.CopyResult_B.setObjectName(u"CopyResult_B")
        self.splitter.addWidget(self.CopyResult_B)
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(390, 470, 431, 23))
        self.progressBar.setValue(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 844, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.load_B.clicked.connect(MainWindow.loadAPIs)
        self.Clear.clicked.connect(self.ResultListView.clear)
        self.browse_B.clicked.connect(MainWindow.selectFile)
        self.VT_GetDomain_B.clicked.connect(MainWindow.vt_get_domains)
        self.VT_GetIP_B.clicked.connect(MainWindow.vt_get_ips)
        self.ResultListView.doubleClicked.connect(MainWindow.add_result_to_qline)
        self.CopyResult_B.clicked.connect(MainWindow.add_to_clipboard)
        self.scan_all.clicked.connect(MainWindow.scan_hosts)
        self.tableWidget.itemDoubleClicked.connect(MainWindow.open_link_in_browser)
        self.copy_as_csv_B.clicked.connect(MainWindow.copy_as_csv)

        QMetaObject.connectSlotsByName(MainWindow)
        self.row_count = self.tableWidget.rowCount()
        self.completed = 0
        self.VT_Qline.setText("google.com")
        self.filepath.setText("C:\\api.txt")

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"VirusTotal Helper 0.1", None))
        self.VirusTotal_GB.setTitle(QCoreApplication.translate("MainWindow", u"VirusTotal Actions", None))
        self.VT_Qline_L.setText(QCoreApplication.translate("MainWindow", u"IP/Domain :", None))
        self.VT_GetIP_B.setText(QCoreApplication.translate("MainWindow", u"IP", None))
        self.VT_GetDomain_B.setText(QCoreApplication.translate("MainWindow", u"Domain", None))
        self.loadapis.setTitle(QCoreApplication.translate("MainWindow", u"Load APIs", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"loaded : None", None))
        self.load_B.setText(QCoreApplication.translate("MainWindow", u"Load", None))
        self.browse_B.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.about.setTitle(QCoreApplication.translate("MainWindow", u"About", None))
        self.help.setText(QCoreApplication.translate("MainWindow",
                                                     u"This tool help you to query virustotal.com using its API. before using this tool you should load APIs list from a file.",
                                                     None))
        self.scan_all.setText(QCoreApplication.translate("MainWindow", u"Scan All", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Host", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"80/443", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"IP", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Note", None));
        self.copy_as_csv_B.setText(QCoreApplication.translate("MainWindow", u"Copy As CSV", None))
        self.Clear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.CopyResult_B.setText(QCoreApplication.translate("MainWindow", u"Copy Result", None))

    #  actions
    def vt_get_domains(self):
        self.ResultListView.clear()
        # self.tableWidget.clear()
        self.progressBar.setValue(0)
        domain = self.VT_Qline.text()
        try:
            domains = get_domain_info(domain, self.APIS)
            self.ResultListView.addItems(sorted(domains))
        except AttributeError as e:
            print(self.ResultListView.addItem("LOAD APIS BEFORE EVERYTHING."))

    def vt_get_ips(self):
        self.ResultListView.clear()
        self.tableWidget.clear()
        self.progressBar.setValue(0)
        ip = self.VT_Qline.text()
        domains = get_ip_info(ip, choice(self.APIS))
        self.ResultListView.addItems(sorted(domains))

    def add_result_to_qline(self):
        text = self.ResultListView.selectedItems()
        self.VT_Qline.setText(text[0].text())

    def add_to_clipboard(self):
        text = ""
        for i in range(self.ResultListView.count()):
            text += self.ResultListView.item(i).text() + "\n"

        q = QApplication.clipboard()
        q.setText(text)

    def selectFile(self):
        self.filepath.setText(QFileDialog.getOpenFileName()[0])

    def loadAPIs(self):
        path = self.filepath.text()
        self.APIS = []
        with open(path, "r") as f:
            self.APIS = f.read().splitlines()
        self.label.setText("Loaded : OK !")

    def add_host_to_table(self, result):
        current_row = self.row_count
        # insert empty row
        self.tableWidget.insertRow(current_row)
        print(result)
        host, portscan_result, ip_address = result.split(":")
        cell_data = [host, portscan_result, ip_address, "BLANK"]
        print(cell_data)
        for k in ([0, 1, 2, 3]):
            self.tableWidget.setItem(
                current_row,
                k,
                QTableWidgetItem(cell_data[k]),
            )
            if portscan_result != '':
                self.tableWidget.item(current_row, k).setBackground(QColor(66, 245, 66))
            else:
                self.tableWidget.item(current_row, k).setBackground(QColor(245, 105, 66))



    def scan_hosts(self):

        # self.tableWidget.clear()
        self.progressBar.setValue(0)
        self.hosts = []
        if self.ResultListView.count() > 2:
            for i in range(self.ResultListView.count()):
                self.hosts.append(self.ResultListView.item(i).text())
        self.thread = QThread()
        self.worker = ScannerThread(hosts=self.hosts, ports=[80, 443])
        self.worker.moveToThread(self.thread)
        self.thread.started.connect(self.worker.run)
        self.worker.finished.connect(self.thread.quit)
        self.worker.finished.connect(self.worker.deleteLater)
        self.thread.finished.connect(self.thread.deleteLater)
        self.worker.result_signal.connect(self.add_host_to_table)

        self.thread.start()
        self.worker.finished.connect(

            lambda: self.worker.progress_signal.connect(self.progressBar.setValue)

        )



    def open_link_in_browser(self):
        r = self.tableWidget.currentRow()
        URL = self.tableWidget.item(r, 0).text()
        ports = self.tableWidget.item(r, 1).text()
        if ports.count("443") >= 1:
            webbrowser.open_new_tab("https://{}/".format(URL))
        elif ports.count("80") >= 1:
            webbrowser.open_new_tab("http://{}/".format(URL))
        else:
            pass

    def copy_as_csv(self):
        path, _ = QFileDialog.getSaveFileName(self, 'Save File', QDir.homePath() + "/export.csv",
                                              "CSV Files(*.csv *.txt)")
        if path:
            with open(path, 'w') as stream:
                print("saving", path)
                writer = csv.writer(stream, delimiter='\t')
                headers = []
                for column in range(self.tableWidget.columnCount()):
                    header = self.tableWidget.horizontalHeaderItem(column)
                    if header is not None:
                        headers.append(header.text())
                    else:
                        headers.append("Column " + str(column))
                writer.writerow(headers)
                for row in range(self.tableWidget.rowCount()):
                    rowdata = []
                    for column in range(self.tableWidget.columnCount()):
                        item = self.tableWidget.item(row, column)
                        if item is not None:
                            rowdata.append(item.text())
                        else:
                            rowdata.append('')
                    writer.writerow(rowdata)


app = QApplication(sys.argv)

window = Ui_MainWindow()
window.setupUi(window)

window.show()

app.exec()
